/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Board: typeof import('./components/Board.vue')['default']
    BoardControls: typeof import('./components/BoardControls.vue')['default']
    BoardControlsSvgDownload: typeof import('./components/BoardControlsSvgDownload.vue')['default']
    BoardControlsSvgDownloadModalContent: typeof import('./components/BoardControlsSvgDownloadModalContent.vue')['default']
    BoardControlsSvgHelp: typeof import('./components/BoardControlsSvgHelp.vue')['default']
    BoardResult: typeof import('./components/BoardResult.vue')['default']
    BoardSummaryItem: typeof import('./components/BoardSummaryItem.vue')['default']
    BoardSvg: typeof import('./components/BoardSvg.vue')['default']
    Button: typeof import('./components/Button.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    Header: typeof import('./components/Header.vue')['default']
    Line: typeof import('./components/Line.vue')['default']
    Modal: typeof import('./components/Modal.vue')['default']
    README: typeof import('./components/README.md')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Segment: typeof import('./components/Segment.vue')['default']
  }
}
