// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Board: typeof import('./components/Board.vue')['default']
    BoardHint: typeof import('./components/BoardHint.vue')['default']
    BoardNav: typeof import('./components/BoardNav.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    Header: typeof import('./components/Header.vue')['default']
    Line: typeof import('./components/Line.vue')['default']
    README: typeof import('./components/README.md')['default']
    Segment: typeof import('./components/Segment.vue')['default']
  }
}
