name: Deploy

on:
  push:
    branches:
      - main
    paths:
      - '.github/**/*'
      - 'patches/**/*'
      - 'packages/**/*'
      - 'pnpm-lock.yaml'
      - 'pnpm-workspace.yaml'
      - 'tsconfig.json'
      - '.npmrc'

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
      - uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: pnpm
      - run: pnpm install
      - run: pnpm build

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: deploy
          FOLDER: packages/web/dist
      - name: get hash of last commit to main
        id: commit_hash
        run: echo "commit_hash=$(git log -1 --skip 1 --format='%H')" >> $GITHUB_OUTPUT
      - uses: dorny/paths-filter@v3
        id: changes
        with:
          base: ${{ steps.commit_hash.outputs.commit_hash }}
          filters: |
            src:
              - '.github/workflows/deploy.yml'
              - 'patches/**'
              - 'packages/web/**'
              - 'tsconfig.json'
            android:
              - '.github/actions/deploy-to-google-play/action.yml'
              - 'packages/android/**'
            ios:
              - 'packages/ios/**'
      - uses: ./.github/actions/deploy-to-google-play
        if: env.DEPLOYMENT_STATUS == 'success' && (steps.changes.outputs.src == 'true' || steps.changes.outputs.android == 'true')
        with:
          keystore-base64: ${{ secrets.ANDROID_DEPLOY_KEYSTORE_BASE64 }}
          keystore-password: ${{ secrets.ANDROID_DEPLOY_KEYSTORE_PASSWD }}
          service-account-key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

